monitor=,preferred,auto,1

#eval $(gnome-keyring-daemon --start)
#export SSH_AUTH_SOCK

env = GTK_THEME,Catppuccin-Mocha
env = QT_QPA_PLATFORMTHEME,gtk2
env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,24

exec-once = waybar
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = swww-daemon & sleep 1 && swww img ~/.config/hypr/wallpaper.jpg
exec-once = nm-applet & blueman-applet
exec-once = hyprctl setcursor Miku-Cursor 24
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

input {
  kb_layout = us
  follow_mouse = yes
  touchpad {
    natural_scroll = yes
  }
}

general {
  gaps_in = 6
  gaps_out = 14
  border_size = 2
  col.active_border = rgba(33ccffee) rgba(ff99ccff) 45deg
  col.inactive_border = rgba(44444488)
}

decoration {
  rounding = 8
  blur {
    enabled = true
    size = 6
    passes = 3
  }
}

# Layer rules for ironbar
layerrule = blur, ironbar
layerrule = ignorezero, ironbar
layerrule = noanim, ironbar

windowrulev2 = float, class:.*
windowrulev2 = moveonce, class:.*
windowrulev2 = size 80% 80%, class:.*

animations {
    enabled = yes
    bezier = ease, 0.25, 0.1, 0.25, 1
    animation = windows, 1, 3, ease         # opening/closing windows
    animation = windowsMove, 1, 4, default  # dragging windows
    animation = border, 1, 10, default
    animation = fade, 1, 10, default        # fade in/out
    animation = workspaces, 1, 6, ease      # switching workspaces
}

bind = SUPER, Return, exec, kitty
bind = SUPER, Q, killactive,
bind = SUPER, E, exec, thunar
bind = SUPER, W, exec, brave
bind = SUPER, R, exec, rofi -show drun -theme miku-launcher
bind = SUPER_SHIFT, Q, exec, systemctl poweroff
bind = SUPER_SHIFT, R, exec, systemctl reboot
bind = SUPER_SHIFT, E, exit
bind = SUPER, UP, exec, pamixer -i 5
bind = SUPER, DOWN, exec, pamixer -d 5
bind = SUPER, M, exec, pamixer -t
bind = SUPER, Print, exec, grim -g "$(slurp)" ~/Pictures/screenshot.png

# Workspaces
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8

# Move to workspaces
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2

bindle = , XF86AudioRaiseVolume, exec, pamixer -i 5
bindle = , XF86AudioLowerVolume, exec, pamixer -d 5
bindle = , XF86AudioMute, exec, pamixer -t

bindm = Super, mouse:272, movewindow
bindm = Super, mouse:273, resizewindow

misc {
  vfr = true
  disable_hyprland_logo = true
}
